// Question pairs for Question Imposter. The two questions in a pair must take the same shape of
// answer (a number, a name, a food, a yes/no) so the odd answer sounds plausible on its own and only
// stands out next to the others. Ids are stable; keep them if the wording is edited.
export interface QuestionPair { id: string; friends: string; imposter: string; }
export const questionPairs: QuestionPair[] = [
  { id: 'sleep-coffee', friends: 'How many hours do you sleep on a normal night?', imposter: 'How many coffees or teas do you drink in a day?' },
  { id: 'countries-cousins', friends: 'How many countries have you been to?', imposter: 'How many cousins do you have?' },
  { id: 'cooking-driving', friends: 'Rate your cooking from 1 to 10.', imposter: 'Rate your driving from 1 to 10.' },
  { id: 'pizza-lastmeal', friends: 'What is your favourite pizza topping?', imposter: 'What was the last thing you ate?' },
  { id: 'wake-bed', friends: 'What time do you usually wake up?', imposter: 'What time do you usually go to bed?' },
  { id: 'celeb-dinner', friends: 'Which celebrity would you invite to dinner?', imposter: 'Which celebrity do you think you look like?' },
  { id: 'fear-hate', friends: 'What is your biggest fear?', imposter: 'What is the worst chore in the house?' },
  { id: 'spend-pay', friends: 'What is the most you would spend on a pair of shoes?', imposter: 'What is the most you would spend on a birthday present for a friend?' },
  { id: 'song-shower', friends: 'What song do you sing in the shower?', imposter: 'What song would you play at your own party?' },
  { id: 'kids-pets', friends: 'How many kids would you like to have?', imposter: 'How many pets would you like to have?' },
  { id: 'unread-tabs', friends: 'How many unread messages do you have right now?', imposter: 'How many browser tabs do you have open right now?' },
  { id: 'city-live', friends: 'Which city would you move to tomorrow?', imposter: 'Which city would you never move to?' },
  { id: 'superpower-wish', friends: 'Which superpower would you choose?', imposter: 'Which superpower would you give to your best friend?' },
  { id: 'animal-self', friends: 'Which animal are you most like?', imposter: 'Which animal is the person on your left most like?' },
  { id: 'holiday-weekend', friends: 'Where did you go on your last holiday?', imposter: 'Where would you go for a weekend if it were free?' },
  { id: 'age-feel', friends: 'How old do you feel today?', imposter: 'At what age did you have your best birthday?' },
  { id: 'exes-jobs', friends: 'How many jobs have you had?', imposter: 'How many phones have you owned?' },
  { id: 'dish-cook', friends: 'What dish do you cook best?', imposter: 'What dish do you order most often?' },
  { id: 'drink-order', friends: 'What is your usual drink order?', imposter: 'What is your usual coffee-shop order?' },
  { id: 'movie-cry', friends: 'Which film made you cry?', imposter: 'Which film have you seen the most times?' },
  { id: 'colour-car', friends: 'What colour would you paint your bedroom?', imposter: 'What colour would you choose for a car?' },
  { id: 'minutes-ready', friends: 'How many minutes do you need to get ready in the morning?', imposter: 'How many minutes late are you, on average?' },
  { id: 'phone-check', friends: 'How many times a day do you check your phone?', imposter: 'How many photos did you take last week?' },
  { id: 'gift-want', friends: 'What do you want for your next birthday?', imposter: 'What is the best gift you have ever given?' },
  { id: 'lie-told', friends: 'What is the last white lie you told?', imposter: 'What is the last excuse you used to leave early?' },
  { id: 'app-delete', friends: 'Which app could you not live without?', imposter: 'Which app do you wish you could delete?' },
  { id: 'hobby-child', friends: 'What hobby would you pick up if you had the time?', imposter: 'What hobby did you have as a kid?' },
  { id: 'steps-flights', friends: 'How many steps do you walk on an average day?', imposter: 'How many stairs do you climb on an average day?' },
  { id: 'sport-watch', friends: 'Which sport do you like to watch?', imposter: 'Which sport were you worst at in school?' },
  { id: 'season-fav', friends: 'What is your favourite season?', imposter: 'Which season has your favourite holiday?' },
  { id: 'name-child', friends: 'What would you name a child?', imposter: 'What would you name a boat?' },
  { id: 'money-found', friends: 'What is the largest amount of money you have found?', imposter: 'What is the largest amount of money you have lost?' },
  { id: 'teacher-fav', friends: 'Which school subject did you love?', imposter: 'Which school subject would you teach?' },
  { id: 'text-last', friends: 'Who was the last person you texted?', imposter: 'Who would you call first with big news?' },
  { id: 'meal-last', friends: 'What would you choose as your last meal?', imposter: 'What did you eat for breakfast today?' },
  { id: 'car-first', friends: 'What was your first car, or dream first car?', imposter: 'What car would you buy with a lottery win?' },
  { id: 'hours-work', friends: 'How many hours did you work this week?', imposter: 'How many hours did you spend on your phone this week?' },
  { id: 'bad-habit', friends: 'What is your worst habit?', imposter: 'What habit annoys you most in other people?' },
  { id: 'streaming-show', friends: 'Which show are you watching right now?', imposter: 'Which show would you recommend to everyone here?' },
  { id: 'temperature-shower', friends: 'How hot do you have your shower, 1 to 10?', imposter: 'How spicy do you like your food, 1 to 10?' },
  { id: 'friends-count', friends: 'How many close friends do you have?', imposter: 'How many people have a key to your home?' },
  { id: 'fruit-fav', friends: 'What is your favourite fruit?', imposter: 'Which fruit do you refuse to eat?' },
  { id: 'language-learn', friends: 'Which language would you like to learn?', imposter: 'Which language sounds the nicest?' },
  { id: 'concert-first', friends: 'What was the first concert you went to?', imposter: 'Which artist would you see live tomorrow?' },
  { id: 'board-game', friends: 'What is your favourite board game?', imposter: 'Which game are you unbeatable at?' },
  { id: 'travel-time', friends: 'How long is your commute?', imposter: 'How long could you sit in a car without stopping?' },
  { id: 'coins-pocket', friends: 'How much cash do you have on you right now?', imposter: 'How much did your last takeaway cost?' },
  { id: 'famous-for', friends: 'What would you like to be famous for?', imposter: 'What are you known for among your friends?' },
  { id: 'era-live', friends: 'Which decade would you like to live in?', imposter: 'Which decade had the best music?' },
  { id: 'clothes-shoes', friends: 'How many pairs of shoes do you own?', imposter: 'How many jackets do you own?' },
  { id: 'island-item', friends: 'What would you bring to a desert island?', imposter: 'What would you grab first if your house was on fire?' },
  { id: 'nickname-child', friends: 'What was your childhood nickname?', imposter: 'What would you like people to call you?' },
  { id: 'dessert-fav', friends: 'What is your favourite dessert?', imposter: 'What dessert would you serve at a wedding?' },
  { id: 'guilty-pleasure', friends: 'What is your guilty-pleasure song?', imposter: 'What is your go-to karaoke song?' },
  { id: 'weather-fav', friends: 'What is your ideal weather?', imposter: 'What weather makes you cancel plans?' },
  { id: 'pet-name', friends: 'What would you name a dog?', imposter: 'What would you name a cat?' },
  { id: 'hours-tv', friends: 'How many hours of TV do you watch a week?', imposter: 'How many hours do you exercise a week?' },
  { id: 'room-clean', friends: 'How tidy is your room, 1 to 10?', imposter: 'How tidy is your car or bag, 1 to 10?' },
  { id: 'job-child', friends: 'What did you want to be when you were little?', imposter: 'What job would you do for a year, just for fun?' },
  { id: 'bring-party', friends: 'What do you bring to a party?', imposter: 'What do you always forget to bring on a trip?' },
];
