// Two groups of categories. Core packs are the everyday game; themed packs ride a season or a
// fandom and each has its own crawlable page under /packs/. "Mixed bag" draws from free core packs
// only, so a themed word never turns up in an ordinary round. Themed packs are free on purpose: they
// are the content creators reach for, and the paywall is the player cap and custom packs.
export const categories = [
  { id: 'mixed', name: 'A little of everything', short: 'Mixed bag', hint: 'A surprise from every category', premium: false, group: 'core', drawable: true },
  { id: 'food', name: 'Food & drink', short: 'Food & drink', hint: 'Something delicious', premium: false, group: 'core', drawable: true },
  { id: 'animals', name: 'Animal kingdom', short: 'Animals', hint: 'Something in the animal kingdom', premium: false, group: 'core', drawable: true },
  { id: 'everyday', name: 'Everyday life', short: 'Everyday', hint: 'Something from everyday life', premium: false, group: 'core', drawable: true },
  { id: 'places', name: 'Out & about', short: 'Places', hint: 'Somewhere you can go', premium: true, group: 'core', drawable: true },
  { id: 'objects', name: 'Everyday things', short: 'Objects', hint: 'An object you might recognize', premium: true, group: 'core', drawable: true },
  { id: 'activities', name: 'Things we do', short: 'Activities', hint: 'Something people do', premium: true, group: 'core', drawable: true },
  { id: 'date-night', name: 'Date night', short: 'Date night', hint: 'Something for a romantic evening', premium: true, group: 'core', drawable: false },
  { id: 'holidays', name: 'Holidays & celebrations', short: 'Holidays', hint: 'Something festive', premium: true, group: 'core', drawable: true },
  { id: 'halloween', name: 'Halloween', short: 'Halloween', hint: 'Something spooky', premium: false, group: 'themed', drawable: true },
  { id: 'football', name: 'Football', short: 'Football', hint: 'Something from the beautiful game', premium: false, group: 'themed', drawable: false },
  { id: 'k-pop', name: 'K-pop', short: 'K-pop', hint: 'Something from the K-pop world', premium: false, group: 'themed', drawable: false },
  { id: 'pop-superstars', name: 'Pop superstars', short: 'Pop hits', hint: 'A pop hit, album, era, or star', premium: false, group: 'themed', drawable: false },
  { id: 'christmas', name: 'Christmas', short: 'Christmas', hint: 'Something Christmassy', premium: false, group: 'themed', drawable: true },
  { id: 'brainrot', name: 'Brainrot', short: 'Brainrot', hint: 'Something the internet says', premium: false, group: 'themed', drawable: false },
  { id: 'night-out', name: 'Night out', short: 'Night out', hint: 'Something from a big night out', premium: false, group: 'themed', drawable: false },
  { id: 'office', name: 'Office & work', short: 'Office', hint: 'Something from the office', premium: false, group: 'themed', drawable: false },
  { id: 'american-football', name: 'American football', short: 'Gridiron', hint: 'Something from American football', premium: false, group: 'themed', drawable: false },
  { id: 'bachelorette', name: 'Hen do & bachelorette', short: 'Hen do', hint: 'Something from a hen do or bachelorette party', premium: false, group: 'themed', drawable: false },
  { id: 'anime', name: 'Anime', short: 'Anime', hint: 'Something from anime and manga', premium: false, group: 'themed', drawable: false },
  { id: 'brands', name: 'Fast food & brands', short: 'Brands', hint: 'A brand or a fast-food order', premium: false, group: 'themed', drawable: false },
  { id: 'movies', name: 'Movies & TV', short: 'Movies & TV', hint: 'Something from movies and TV', premium: false, group: 'themed', drawable: false },
] as const;
export type Category = typeof categories[number]['id'];
export interface Word { id: string; text: string; category: Exclude<Category, 'mixed'>; }
const packs: Record<Exclude<Category, 'mixed'>, string[]> = {
  food: ['Pizza', 'Popcorn', 'Chocolate', 'Sushi', 'Pancake', 'Watermelon', 'Ice cream', 'Spaghetti', 'Croissant', 'Lemonade', 'Taco', 'Cheese', 'Honey', 'Pretzel', 'Pineapple', 'Doughnut', 'Coffee', 'Avocado', 'Waffle', 'Cookie', 'Soup', 'Grapes', 'Sandwich', 'Cereal', 'Lasagne', 'Burrito', 'Dumplings', 'Ramen', 'Bagel', 'Muffin', 'Brownie', 'Cheesecake', 'Tiramisu', 'Macaron', 'Cupcake', 'Pie', 'Toast', 'Omelette', 'Fried chicken', 'Hot dog', 'Burger', 'Kebab', 'Curry', 'Risotto', 'Paella', 'Noodles', 'Salad', 'Guacamole', 'Hummus', 'Olives', 'Pickle', 'Mango', 'Strawberry', 'Banana', 'Cherry', 'Coconut', 'Peach', 'Lemon', 'Garlic', 'Onion', 'Mushroom', 'Potato', 'Corn on the cob', 'Rice', 'Bread', 'Butter', 'Yoghurt', 'Milkshake', 'Smoothie', 'Tea', 'Hot chocolate', 'Orange juice', 'Cola', 'Bubble tea', 'Popsicle', 'Marshmallow', 'Gummy bears', 'Lollipop', 'Peanut butter', 'Jam'],
  animals: ['Penguin', 'Elephant', 'Octopus', 'Giraffe', 'Butterfly', 'Dolphin', 'Kangaroo', 'Flamingo', 'Hedgehog', 'Chameleon', 'Jellyfish', 'Panda', 'Owl', 'Crocodile', 'Squirrel', 'Peacock', 'Turtle', 'Seahorse', 'Camel', 'Bee', 'Fox', 'Rabbit', 'Snail', 'Bat', 'Lion', 'Tiger', 'Wolf', 'Bear', 'Polar bear', 'Gorilla', 'Monkey', 'Sloth', 'Koala', 'Zebra', 'Hippo', 'Rhino', 'Cheetah', 'Leopard', 'Deer', 'Moose', 'Horse', 'Donkey', 'Cow', 'Pig', 'Sheep', 'Goat', 'Chicken', 'Duck', 'Swan', 'Parrot', 'Eagle', 'Hawk', 'Pigeon', 'Crow', 'Hummingbird', 'Frog', 'Toad', 'Lizard', 'Snake', 'Iguana', 'Shark', 'Whale', 'Seal', 'Otter', 'Lobster', 'Crab', 'Starfish', 'Clownfish', 'Eel', 'Ant', 'Spider', 'Ladybird', 'Mosquito', 'Moth', 'Dragonfly', 'Worm', 'Hamster', 'Guinea pig', 'Mouse', 'Rat'],
  everyday: ['Alarm clock', 'Coffee break', 'Traffic jam', 'Rush hour', 'Umbrella weather', 'Sunday roast', 'Grocery list', 'Self-checkout', 'Loyalty card', 'Receipt', 'Queue', 'Lift', 'Escalator', 'Revolving door', 'Doorbell', 'Neighbour', 'Landlord', 'Rent day', 'Recycling bin', 'Bin day', 'Lost keys', 'Spare key', 'Dead battery', 'Wi-Fi password', 'Group chat', 'Voice note', 'Missed call', 'Selfie', 'Screenshot', 'Autocorrect', 'Spam email', 'Password reset', 'Zoom call', 'Meeting', 'Deadline', 'Lunch break', 'Payday', 'Overtime', 'Sick day', 'Homework', 'Exam', 'School run', 'Packed lunch', 'Detention', 'Library card', 'Dentist appointment', 'Haircut', 'Laundry day', 'Odd sock', 'Ironing', 'Dishwasher', 'Leftovers', 'Takeaway', 'Delivery driver', 'Doorstep parcel', 'Wrong address', 'Junk drawer', 'Spring cleaning', 'Houseplant', 'Pet hair', 'Dog walk', 'Litter tray', 'Morning run', 'Gym membership', 'Step count', 'Snooze button', 'Late night snack', 'Netflix binge', 'Spoiler', 'Playlist', 'Earphones', 'Charger cable', 'Bus pass', 'Parking ticket', 'Speed bump', 'Roundabout', 'Road trip', 'Boarding pass', 'Airport security', 'Jet lag', 'Suitcase wheel', 'Hotel breakfast', 'Souvenir', 'Postcard', 'Sunburn', 'Mosquito bite', 'Rainy day', 'Heatwave', 'Snow day', 'Power cut', 'Birthday reminder', 'Secret Santa', 'Housewarming gift', 'Thank-you note', 'Small talk', 'Awkward silence', 'Inside joke', 'Nickname', 'Handshake', 'High five', 'Yawn', 'Hiccups', 'Sneeze', 'Bad hair day'],
  places: ['Library', 'Airport', 'Beach', 'Museum', 'Cinema', 'Supermarket', 'Lighthouse', 'Castle', 'Aquarium', 'Bakery', 'Playground', 'Train station', 'Desert', 'Waterfall', 'Campsite', 'Stadium', 'Treehouse', 'Restaurant', 'Mountain', 'Zoo', 'Garden', 'Swimming pool', 'Farm', 'Island', 'Hospital', 'School', 'Office', 'Gym', 'Theatre', 'Concert hall', 'Nightclub', 'Casino', 'Hotel', 'Hostel', 'Cafe', 'Pub', 'Food truck', 'Market', 'Shopping mall', 'Petrol station', 'Car wash', 'Garage', 'Bus stop', 'Harbour', 'Ferry', 'Subway', 'Bridge', 'Tunnel', 'Skyscraper', 'Cathedral', 'Temple', 'Cemetery', 'Prison', 'Courtroom', 'Police station', 'Fire station', 'Post office', 'Bank', 'Pharmacy', 'Dentist', 'Hair salon', 'Laundromat', 'Bookshop', 'Toy shop', 'Ice rink', 'Bowling alley', 'Arcade', 'Theme park', 'Water park', 'Circus', 'Ski resort', 'Volcano', 'Cave', 'Jungle', 'Canyon', 'Glacier', 'Lake', 'River', 'Vineyard', 'Orchard'],
  objects: ['Umbrella', 'Telescope', 'Toothbrush', 'Backpack', 'Candle', 'Scissors', 'Guitar', 'Mirror', 'Headphones', 'Compass', 'Camera', 'Ladder', 'Bicycle', 'Pillow', 'Kite', 'Suitcase', 'Key', 'Clock', 'Sunglasses', 'Balloon', 'Book', 'Magnet', 'Paintbrush', 'Teapot', 'Laptop', 'Phone charger', 'Remote control', 'Batteries', 'Lightbulb', 'Extension cord', 'Hairdryer', 'Toaster', 'Kettle', 'Fridge', 'Microwave', 'Blender', 'Frying pan', 'Chopsticks', 'Corkscrew', 'Thermos', 'Lunchbox', 'Wallet', 'Passport', 'Ticket', 'Stamp', 'Envelope', 'Notebook', 'Pencil', 'Stapler', 'Calculator', 'Ruler', 'Glue stick', 'Tape', 'Whiteboard', 'Trophy', 'Medal', 'Piggy bank', 'Dice', 'Playing cards', 'Puzzle', 'Teddy bear', 'Skateboard', 'Helmet', 'Tent', 'Sleeping bag', 'Torch', 'Binoculars', 'Fishing rod', 'Hammer', 'Screwdriver', 'Drill', 'Wheelbarrow', 'Hose', 'Broom', 'Vacuum cleaner', 'Bucket', 'Doormat', 'Curtains', 'Alarm clock', 'Hammock'],
  activities: ['Camping', 'Dancing', 'Swimming', 'Gardening', 'Baking', 'Fishing', 'Skiing', 'Painting', 'Bowling', 'Surfing', 'Hiking', 'Singing', 'Knitting', 'Skateboarding', 'Reading', 'Yoga', 'Juggling', 'Sailing', 'Chess', 'Karaoke', 'Picnic', 'Running', 'Photography', 'Football', 'Cycling', 'Jogging', 'Rock climbing', 'Bungee jumping', 'Skydiving', 'Scuba diving', 'Snorkelling', 'Kayaking', 'Ice skating', 'Snowboarding', 'Sledging', 'Horse riding', 'Archery', 'Fencing', 'Boxing', 'Wrestling', 'Golf', 'Tennis', 'Basketball', 'Volleyball', 'Badminton', 'Table tennis', 'Darts', 'Pool', 'Poker', 'Bingo', 'Sudoku', 'Crossword', 'Video games', 'Board games', 'Drawing', 'Sculpting', 'Pottery', 'Origami', 'Sewing', 'Woodwork', 'Cooking', 'Grilling', 'Wine tasting', 'Bird watching', 'Stargazing', 'Meditation', 'Sunbathing', 'Window shopping', 'Thrifting', 'Busking', 'Beatboxing', 'DJing', 'Ballet', 'Breakdancing', 'Cheerleading', 'Magic tricks', 'Stand-up comedy', 'Acting', 'Podcasting', 'Vlogging'],
  'date-night': ['Candlelight', 'Bouquet', 'Serenade', 'Sunset walk', 'Slow dance', 'Love letter', 'First kiss', 'Rooftop dinner', 'Wine tasting', 'Stargazing', 'Proposal', 'Anniversary', 'Chocolate fondue', 'Rose', 'Piano bar', 'Movie night', 'Hand-holding', 'Fireplace', 'Karaoke duet', 'Picnic blanket', 'Photo booth', 'Long-distance call', 'Blind date', 'Honeymoon', 'Sunrise hike', 'Cooking together', 'Dessert for two', 'Long drive', 'Ferris wheel', 'Rooftop bar', 'Jazz club', 'Ice cream date', 'Hot tub', 'Bubble bath', 'Breakfast in bed', 'Couples massage', 'Ballroom dancing', 'Salsa class', 'Pottery date', 'Paint and sip', 'Escape room date', 'Mini golf', 'Bowling date', 'Board game night', 'Fancy dress', 'Flower crown', 'Love song', 'Mixtape', 'Matching pyjamas', 'Weekend away', 'Beach picnic', 'Ferry ride', 'Lantern release', 'Fortune cookie', 'Cheese board', 'Champagne toast', 'Balcony breakfast'],
  halloween: ['Pumpkin', 'Jack-o’-lantern', 'Witch', 'Broomstick', 'Cauldron', 'Black cat', 'Vampire', 'Werewolf', 'Zombie', 'Mummy', 'Ghost', 'Skeleton', 'Haunted house', 'Graveyard', 'Tombstone', 'Coffin', 'Spider web', 'Bat', 'Full moon', 'Scarecrow', 'Trick-or-treat', 'Candy corn', 'Costume', 'Mask', 'Fake blood', 'Fog machine', 'Ouija board', 'Crystal ball', 'Fortune teller', 'Frankenstein', 'Grim reaper', 'Scythe', 'Potion', 'Spell book', 'Cobweb', 'Haunted maze', 'Horror movie', 'Jump scare', 'Creepy clown', 'Chainsaw', 'Trapdoor', 'Creaky door', 'Raven', 'Wolf howl', 'Candy bucket', 'Doorbell', 'Ghost story', 'Hearse'],
  football: ['Penalty', 'Free kick', 'Corner kick', 'Offside', 'Red card', 'Yellow card', 'Own goal', 'Hat-trick', 'Golden Boot', 'Clean sheet', 'Goalkeeper', 'Striker', 'Winger', 'Captain’s armband', 'Referee', 'VAR', 'Extra time', 'Penalty shootout', 'Stoppage time', 'Derby', 'Champions League', 'World Cup', 'Premier League', 'Transfer window', 'Mascot', 'Stadium', 'Dugout', 'Half-time', 'Nutmeg', 'Bicycle kick', 'Header', 'Volley', 'Sliding tackle', 'Dive', 'Throw-in', 'Defensive wall', 'Crossbar', 'Top corner', 'Season ticket', 'Away end', 'Chant', 'Scarf', 'Home kit', 'Shin pads', 'Manager', 'Substitute', 'Relegation', 'Ballon d’Or', 'Goal-line technology', 'Penalty box', 'Six-yard box', 'Kick-off', 'Coin toss', 'Handshake', 'Anthem', 'Line-up', 'Formation', 'Set piece', 'Counter-attack', 'Long ball', 'Through ball', 'Back pass', 'Rabona', 'Panenka', 'Clean strike', 'Rebound', 'Deflection', 'Goal kick', 'Injury time', 'Man of the match', 'Golden goal', 'Aggregate', 'Play-offs', 'Promotion', 'Treble', 'Invincibles', 'Underdogs', 'Tifo', 'Pitch invasion', 'Half-time pie'],
  'k-pop': ['Bias', 'Bias wrecker', 'Comeback', 'Lightstick', 'Fan chant', 'Photocard', 'Maknae', 'Leader', 'Visual', 'Main vocal', 'Rap line', 'Choreography', 'Point dance', 'Title track', 'B-side', 'Music show', 'Encore', 'Fan sign', 'Trainee', 'Debut', 'Aegyo', 'Sub-unit', 'Concept photo', 'Teaser', 'Album unboxing', 'Fandom name', 'Lightstick ocean', 'Kill part', 'Line distribution', 'Idol', 'Survival show', 'Center', 'Ending fairy', 'Selca', 'BTS', 'Blackpink', 'Stray Kids', 'NewJeans', 'Twice', 'Seventeen', 'aespa', 'EXO', 'Red Velvet', 'Le Sserafim', 'ITZY', 'NCT', 'Enhypen', 'IVE', 'Photobook', 'Pre-order', 'Fan cafe', 'Fan meeting', 'Fansite', 'Lightstick battery', 'Comeback stage', 'Dance practice video', 'Relay dance', 'Random play dance', 'Cover dance', 'High note', 'Ad-lib', 'Killing part', 'Concept trailer', 'Highlight medley', 'Tracklist', 'Repackage', 'Special stage', 'Award show', 'Daesang', 'Rookie of the year', 'Hiatus', 'Solo debut', 'Variety show', 'Idol reality show', 'Weverse', 'Dance challenge', 'Hashtag trend', 'Stan', 'Sasaeng', 'Bias list'],
  'pop-superstars': ['Anti-Hero', 'Cruel Summer', 'Folklore', 'Eras Tour', 'Love Story', 'Shake It Off', 'Espresso', 'Flowers', 'Bad Guy', 'Drivers License', 'Renaissance', 'Single Ladies', 'Umbrella', 'Diamonds', 'Blinding Lights', 'Uptown Funk', 'Rolling in the Deep', 'Toxic', 'Poker Face', 'Bad Romance', 'Thriller', 'Billie Jean', 'Like a Prayer', 'Dancing Queen', 'Bohemian Rhapsody', 'Firework', 'Chandelier', 'Levitating', 'Good 4 U', 'Watermelon Sugar', 'As It Was', 'Shape of You', 'Havana', 'Kill Bill', 'Padam Padam', 'Taylor Swift', 'Beyoncé', 'Rihanna', 'Lady Gaga', 'Dua Lipa', 'Harry Styles', 'Billie Eilish', 'Olivia Rodrigo', 'Sabrina Carpenter', 'Chappell Roan', 'Ariana Grande', 'The Weeknd', 'Adele', 'Vampire', 'Greedy', 'Houdini', 'Paint the Town Red', 'About Damn Time', 'Truth Hurts', 'Señorita', 'Perfect', 'Don’t Start Now', 'Happier Than Ever', 'Hello', 'Halo', 'Purple Rain', 'Vogue', 'Roar', 'Sorry', 'Believe', 'Wannabe', 'Baby One More Time', 'Crazy in Love', 'Hips Don’t Lie', 'Since U Been Gone', 'Call Me Maybe', 'Royals', 'Shallow', 'Bad Habits', 'Stay', 'Flowers in your hair', 'Miley Cyrus', 'Katy Perry', 'Justin Bieber', 'Shakira'],
  christmas: ['Christmas tree', 'Mistletoe', 'Stocking', 'Chimney', 'Sleigh', 'Reindeer', 'Rudolph', 'Elf', 'North Pole', 'Snowman', 'Gingerbread house', 'Candy cane', 'Eggnog', 'Mulled wine', 'Turkey dinner', 'Cranberry sauce', 'Brussels sprouts', 'Christmas pudding', 'Mince pie', 'Advent calendar', 'Wreath', 'Tinsel', 'Bauble', 'Fairy lights', 'Star on top', 'Nativity scene', 'Carol singers', 'Secret Santa', 'Wrapping paper', 'Ugly sweater', 'Christmas market', 'Ice skating', 'Snowball fight', 'Hot chocolate', 'Nutcracker', 'The Grinch', 'Home Alone', 'Santa’s workshop', 'Naughty list', 'Letter to Santa', 'Christmas Eve', 'Boxing Day', 'Christmas cracker', 'Paper crown', 'Yule log', 'Snow globe', 'Sledging', 'Roast chestnuts'],
  brainrot: ['6-7', 'Rizz', 'Rizzler', 'Aura', 'Aura farming', 'Sigma', 'What the sigma', 'Skibidi', 'Skibidi Toilet', 'Ohio', 'Fanum tax', 'NPC', 'Delulu', 'Cooked', 'Chopped', 'Crash out', 'Lock in', 'Ate', 'Slay', 'No cap', 'Bet', 'Mid', 'Ratio', 'Touch grass', 'Main character', 'Side quest', 'It’s giving', 'The ick', 'Situationship', 'Yapping', 'Glazing', 'Mewing', 'Looksmaxxing', 'Mogging', 'Unc', 'Opp', 'Pookie', 'Tuff', 'Clanker', 'Labubu', 'Dubai chocolate', 'Matcha', 'Brat summer', 'Griddy', 'Doomscrolling', 'Sus', 'Bussin', 'GOAT', 'Stan', 'Lowkey', 'Brainrot', 'Italian brainrot', 'Tralalero Tralala', 'Tung Tung Tung Sahur', 'Bombardiro Crocodilo', 'Ballerina Cappuccina', 'Chat, is this real', 'Lore', 'Canon event', 'Rent free', 'Caught in 4K', 'Understood the assignment', 'Very demure', 'Bombastic side eye', 'Chill guy', 'Roman Empire', 'Beige flag', 'Red flag', 'Green flag', 'Girl dinner', 'Soft launch', 'Fit check', 'Drip', 'Vibe check', 'Simp', 'Glow up', 'Goblin mode', 'Hits different', 'Spill the tea', 'Throwing shade'],
  'night-out': ['Pre-drinks', 'Happy hour', 'Two-for-one', 'Tequila shot', 'Round of shots', 'Jägerbomb', 'Pint', 'Cocktail', 'Espresso martini', 'Aperol spritz', 'Prosecco', 'Open tab', 'Bar tab', 'Whose round', 'One more', 'Lightweight', 'Bouncer', 'Fake ID', 'Guest list', 'Queue for the club', 'Cloakroom', 'Stamp on your hand', 'Wristband', 'Sticky floor', 'Smoking area', 'DJ', 'Dance floor', 'Song request', 'Last orders', 'Lock-in', 'Karaoke', 'Pub quiz', 'Beer pong', 'Never have I ever', 'Designated driver', 'Taxi rank', 'Uber rating', 'Split the fare', 'Kebab', 'Chips and cheese', 'Late-night pizza', 'Drive-through', 'Lost phone', 'Cracked screen', 'Dead battery', 'Drunk text', 'Group chat', 'Voice note', 'Photo dump', 'Blurry selfie', 'Toilet selfie', 'Toilet queue', 'Hangover', 'Beer fear', 'Hair of the dog', 'Fry-up', 'Paracetamol', 'Sunglasses indoors', 'Walk of shame', 'Missing shoe', 'Glitter', 'Flat shoes in the bag', 'Heels off', 'Hen party', 'Stag do', 'Birthday drinks', 'Leaving drinks', 'Bottomless brunch', 'Beer garden', 'Table service', 'Bar snacks', 'Afters', 'After-party', 'House party', 'Noise complaint', 'Sunday scaries', 'Dry January', 'Sober October', 'Cheers', 'Wine o’clock'],
  office: ['Per my last email', 'Reply all', 'Out of office', 'Monday morning', 'Friday feeling', 'Team building', 'Away day', 'Icebreaker', 'Stand-up', 'All-hands', 'Town hall', 'One-to-one', 'Performance review', 'KPI', 'Deadline', 'Slack', 'Teams call', 'You’re on mute', 'Camera off', 'Zoom background', 'Calendar invite', 'Double-booked', 'Back-to-back meetings', 'Meeting that could have been an email', 'Agenda', 'Action items', 'Circle back', 'Touch base', 'Synergy', 'Low-hanging fruit', 'Move the needle', 'Bandwidth', 'Quick question', 'Just checking in', 'Deep dive', 'Ping me', 'Loop me in', 'Take this offline', 'Open-plan office', 'Hot desk', 'Standing desk', 'The printer', 'Paper jam', 'Stapler', 'Post-it note', 'Whiteboard', 'Lanyard', 'The fridge', 'Someone’s lunch', 'Passive-aggressive note', 'Birthday cake', 'Leaving card', 'Secret Santa', 'Christmas party', 'Dress-down Friday', 'Lunch at your desk', 'Coffee run', 'Water cooler', 'Vending machine', 'Commute', 'Work from home', 'Return to office', 'Payday', 'Expenses', 'Annual leave', 'Sick day', 'Notice period', 'Exit interview', 'LinkedIn post', 'Intern', 'Middle manager', 'HR', 'Turn it off and on again', 'Password reset', 'Timesheet', 'Overtime', 'Burnout', 'Quiet quitting', 'Promotion', 'Pizza Friday'],
  'american-football': ['Touchdown', 'Field goal', 'Extra point', 'Two-point conversion', 'Safety', 'Interception', 'Fumble', 'Sack', 'Hail Mary', 'Blitz', 'Quarterback', 'Running back', 'Wide receiver', 'Tight end', 'Offensive line', 'Linebacker', 'Cornerback', 'Kicker', 'Punter', 'Huddle', 'Snap', 'Audible', 'Play-action', 'Screen pass', 'Shotgun', 'First down', 'Fourth down', 'Red zone', 'End zone', 'Two-minute warning', 'Overtime', 'Coin toss', 'Kickoff', 'Onside kick', 'Punt return', 'Touchback', 'Flag on the play', 'Pass interference', 'Holding', 'False start', 'Roughing the passer', 'Instant replay', 'Challenge flag', 'Referee', 'Chain gang', 'Sideline', 'Playbook', 'Game film', 'Combine', 'Draft', 'First-round pick', 'Rookie', 'Free agency', 'Trade deadline', 'Salary cap', 'Preseason', 'Bye week', 'Playoffs', 'Wild card', 'Super Bowl', 'Halftime show', 'Super Bowl ad', 'MVP', 'Tailgate', 'Wings', 'Nachos', 'Foam finger', 'Face paint', 'Cheerleaders', 'Marching band', 'Fantasy football', 'Waiver wire', 'Sunday Night Football', 'Monday Night Football', 'Thanksgiving game', 'Gatorade shower', 'Touchdown dance', 'Helmet', 'Shoulder pads', 'Pigskin'],
  bachelorette: ['Bride-to-be', 'Maid of honour', 'Bridesmaids', 'Sash', 'Tiara', 'Veil', 'Team Bride', 'Matching T-shirts', 'Matching pyjamas', 'Bride tribe', 'Group chat', 'Itinerary', 'Spreadsheet', 'Deposit', 'Splitting the bill', 'Airbnb', 'Cottage', 'Spa day', 'Hot tub', 'Face masks', 'Prosecco', 'Bottomless brunch', 'Cocktail class', 'Afternoon tea', 'Life drawing', 'Dance class', 'Karaoke', 'Pub crawl', 'Party bus', 'Limo', 'Boat trip', 'Pool float', 'Weekend away', 'City break', 'Vegas', 'Nashville', 'Ibiza', 'Airport drinks', 'Scavenger hunt', 'Dares list', 'Mr & Mrs quiz', 'Truth or dare', 'Never have I ever', 'Photo booth', 'Polaroids', 'Balloons', 'Banner', 'Confetti', 'Cupcakes', 'Ring pop', 'The bride’s ex', 'The one who cries', 'The organiser', 'The late one', 'The lightweight', 'The mum', 'The one who leaves early', 'Speech', 'Toast', 'Slideshow', 'Embarrassing photos', 'Fancy dress', 'Nineties theme', 'Cowgirl hats', 'Bunny ears', 'Tutu', 'Heels off', 'Uber', 'Hangover', 'Brunch the morning after', 'Wedding', 'Honeymoon', 'Gift registry', 'Stag do', 'Groom', 'Save the date', 'First dance', 'Bouquet toss', 'Something borrowed', 'Engagement ring'],
  anime: ['Naruto', 'One Piece', 'Dragon Ball', 'Attack on Titan', 'Demon Slayer', 'Jujutsu Kaisen', 'My Hero Academia', 'Death Note', 'Pokémon', 'Sailor Moon', 'Studio Ghibli', 'Spirited Away', 'Totoro', 'Bleach', 'Hunter x Hunter', 'Fullmetal Alchemist', 'One Punch Man', 'Chainsaw Man', 'Spy x Family', 'Haikyuu', 'Cowboy Bebop', 'Evangelion', 'Solo Leveling', 'Frieren', 'Dandadan', 'Shonen', 'Shojo', 'Isekai', 'Slice of life', 'Mecha', 'Magical girl', 'Filler episode', 'Tournament arc', 'Training arc', 'Beach episode', 'Power-up', 'Transformation', 'Final form', 'Plot armour', 'Protagonist', 'Rival', 'Sensei', 'Senpai', 'Tsundere', 'Best girl', 'Big bad', 'Chosen one', 'Opening theme', 'Ending theme', 'Sub or dub', 'Manga', 'Light novel', 'Chapter', 'Season finale', 'Cliffhanger', 'Flashback', 'Nosebleed', 'Sweat drop', 'Nani?!', 'Speed lines', 'Cherry blossoms', 'School uniform', 'Ramen', 'Onigiri', 'Bento', 'Convenience store', 'Rooftop lunch', 'Cultural festival', 'Cosplay', 'Convention', 'Figures', 'Gacha', 'Kaiju', 'Ninja', 'Samurai', 'Katana', 'Titan', 'Pirate King', 'Hokage', 'Saiyan', 'Kamehameha', 'Pokédex', 'Pikachu', 'Gym badge'],
  brands: ['Big Mac', 'McFlurry', 'Happy Meal', 'Drive-through', 'Chicken nuggets', 'Whopper', 'Bucket of chicken', 'Footlong sub', 'Pizza tracker', 'Burrito bowl', 'Taco Bell', 'Starbucks', 'Name on the cup', 'Pumpkin spice latte', 'Frappuccino', 'Dunkin’', 'Krispy Kreme', 'Five Guys', 'In-N-Out', 'Shake Shack', 'Nando’s', 'Greggs sausage roll', 'Pret', 'Chick-fil-A', 'Wingstop', 'Popeyes', 'Ben & Jerry’s', 'Oreo', 'Nutella', 'Pringles', 'Doritos', 'Haribo', 'Kinder Egg', 'Toblerone', 'KitKat', 'Coca-Cola', 'Pepsi', 'Red Bull', 'Monster', 'Prime', 'Stanley cup', 'Crocs', 'Nike', 'Adidas', 'Air Force 1', 'Ugg boots', 'Birkenstocks', 'Lululemon', 'Gymshark', 'Zara', 'Primark', 'Shein', 'IKEA', 'IKEA meatballs', 'Flat-pack', 'Amazon', 'Prime Day', 'Temu', 'eBay', 'Apple Store', 'AirPods', 'iPhone', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Netflix', 'Spotify', 'Spotify Wrapped', 'Uber Eats', 'Deliveroo', 'DoorDash', 'Airbnb', 'Tesla', 'Lego', 'Barbie', 'Dyson', 'Costco hot dog', 'Walmart', 'Target', 'Trader Joe’s', 'Tesco meal deal', 'Aldi middle aisle', 'Duolingo owl', 'Wordle'],
  movies: ['Plot twist', 'Post-credits scene', 'Spoiler', 'Cliffhanger', 'Season finale', 'Binge-watch', 'Skip intro', 'Are you still watching?', 'Prequel', 'Sequel', 'Reboot', 'Remake', 'Spin-off', 'Cinematic universe', 'Origin story', 'Villain', 'Sidekick', 'Love interest', 'Final girl', 'Jump scare', 'Slow burn', 'Montage', 'Flashback', 'Voiceover', 'Narrator', 'Plot hole', 'Fourth wall', 'Cameo', 'Easter egg', 'Blooper', 'Deleted scene', 'Director’s cut', 'Trailer', 'Teaser', 'Red carpet', 'The Oscars', 'Popcorn', 'Front row', '3D glasses', 'IMAX', 'Streaming', 'Password sharing', 'Ad break', 'Subtitles', 'Dubbed', 'Laugh track', 'Sitcom', 'Soap opera', 'Reality TV', 'Dating show', 'Cooking show', 'True crime', 'Documentary', 'Rom-com', 'Horror', 'Thriller', 'Musical', 'Superhero movie', 'Box office', 'Flop', 'Cult classic', 'Christmas movie', 'Disaster movie', 'Heist', 'Courtroom drama', 'Period drama', 'Western', 'Zombie apocalypse', 'Time travel', 'Multiverse', 'Found footage', 'Star Wars', 'Harry Potter', 'Lord of the Rings', 'Jurassic Park', 'The Office', 'Friends', 'Stranger Things', 'Breaking Bad', 'Game of Thrones', 'Squid Game', 'The Simpsons', 'Bluey', 'Shrek'],
  holidays: ['Fireworks', 'Christmas tree', 'Menorah', 'Pumpkin', 'Firecracker', 'New Year', 'Easter egg', 'Parade', 'Costume', 'Mistletoe', 'Carnival', 'Lantern festival', 'Turkey dinner', 'Snowman', 'Gift wrap', 'Countdown', 'Candy cane', 'Trick-or-treat', 'Fourth of July', 'Wreath', 'Valentine’s Day', 'Diwali', 'Piñata', 'Harvest festival', 'Birthday cake', 'Surprise party', 'Confetti', 'Balloon arch', 'Party hat', 'Karaoke night', 'Bonfire night', 'Sparkler', 'Easter bunny', 'Chocolate egg', 'Pumpkin pie', 'Gingerbread man', 'Advent wreath', 'Dreidel', 'Diwali lamp', 'Lunar New Year', 'Red envelope', 'Dragon dance', 'Mardi Gras beads', 'St Patrick’s Day', 'Shamrock', 'Mother’s Day', 'Father’s Day', 'Graduation cap', 'Wedding cake', 'First dance', 'Baby shower', 'Housewarming', 'Retirement party', 'Anniversary dinner', 'Toast', 'Champagne', 'Midnight kiss'],
};
export const words: Word[] = Object.entries(packs).flatMap(([category, entries]) => entries.map((text, index) => ({ id: `${category}-${index}`, text, category: category as Word['category'] })));
const mixedCategoryIds = new Set<Word['category']>(categories.filter(category => !category.premium && category.group === 'core' && category.id !== 'mixed').map(category => category.id) as Word['category'][]);
// The free "mixed" pool blends only free core packs: never a premium word for a non-premium
// player, and never a Halloween word in June.
export function getWords(category: Category) {
  if (category === 'mixed') return words.filter(word => mixedCategoryIds.has(word.category));
  return words.filter(word => word.category === category);
}
