// Two groups of categories. Core packs are the everyday game; themed packs ride a season or a
// fandom and each has its own crawlable page under /packs/. "Mixed bag" draws from free core packs
// only, so a themed word never turns up in an ordinary round. Themed packs are free on purpose: they
// are the content creators reach for, and the paywall is the player cap and custom packs.
export const categories = [
  { id: 'mixed', name: 'A little of everything', short: 'Mixed bag', hint: 'A surprise from every category', premium: false, group: 'core', drawable: true },
  { id: 'food', name: 'Food & drink', short: 'Food & drink', hint: 'Something delicious', premium: false, group: 'core', drawable: true },
  { id: 'animals', name: 'Animal kingdom', short: 'Animals', hint: 'Something in the animal kingdom', premium: false, group: 'core', drawable: true },
  { id: 'everyday', name: 'Everyday life', short: 'Everyday', hint: 'Something from everyday life', premium: false, group: 'core', drawable: true },
  { id: 'places', name: 'Out & about', short: 'Places', hint: 'Somewhere you can go', premium: true, group: 'core', drawable: true },
  { id: 'objects', name: 'Everyday things', short: 'Objects', hint: 'An object you might recognize', premium: true, group: 'core', drawable: true },
  { id: 'activities', name: 'Things we do', short: 'Activities', hint: 'Something people do', premium: true, group: 'core', drawable: true },
  { id: 'date-night', name: 'Date night', short: 'Date night', hint: 'Something for a romantic evening', premium: true, group: 'core', drawable: false },
  { id: 'holidays', name: 'Holidays & celebrations', short: 'Holidays', hint: 'Something festive', premium: true, group: 'core', drawable: true },
  { id: 'halloween', name: 'Halloween', short: 'Halloween', hint: 'Something spooky', premium: false, group: 'themed', drawable: true },
  { id: 'football', name: 'Football', short: 'Football', hint: 'Something from the beautiful game', premium: false, group: 'themed', drawable: false },
  { id: 'k-pop', name: 'K-pop', short: 'K-pop', hint: 'Something from the K-pop world', premium: false, group: 'themed', drawable: false },
  { id: 'pop-superstars', name: 'Pop superstars', short: 'Pop hits', hint: 'A pop hit, album, era, or star', premium: false, group: 'themed', drawable: false },
  { id: 'christmas', name: 'Christmas', short: 'Christmas', hint: 'Something Christmassy', premium: false, group: 'themed', drawable: true },
] as const;
export type Category = typeof categories[number]['id'];
export interface Word { id: string; text: string; category: Exclude<Category, 'mixed'>; }
const packs: Record<Exclude<Category, 'mixed'>, string[]> = {
  food: ['Pizza', 'Popcorn', 'Chocolate', 'Sushi', 'Pancake', 'Watermelon', 'Ice cream', 'Spaghetti', 'Croissant', 'Lemonade', 'Taco', 'Cheese', 'Honey', 'Pretzel', 'Pineapple', 'Doughnut', 'Coffee', 'Avocado', 'Waffle', 'Cookie', 'Soup', 'Grapes', 'Sandwich', 'Cereal', 'Lasagne', 'Burrito', 'Dumplings', 'Ramen', 'Bagel', 'Muffin', 'Brownie', 'Cheesecake', 'Tiramisu', 'Macaron', 'Cupcake', 'Pie', 'Toast', 'Omelette', 'Fried chicken', 'Hot dog', 'Burger', 'Kebab', 'Curry', 'Risotto', 'Paella', 'Noodles', 'Salad', 'Guacamole', 'Hummus', 'Olives', 'Pickle', 'Mango', 'Strawberry', 'Banana', 'Cherry', 'Coconut', 'Peach', 'Lemon', 'Garlic', 'Onion', 'Mushroom', 'Potato', 'Corn on the cob', 'Rice', 'Bread', 'Butter', 'Yoghurt', 'Milkshake', 'Smoothie', 'Tea', 'Hot chocolate', 'Orange juice', 'Cola', 'Bubble tea', 'Popsicle', 'Marshmallow', 'Gummy bears', 'Lollipop', 'Peanut butter', 'Jam'],
  animals: ['Penguin', 'Elephant', 'Octopus', 'Giraffe', 'Butterfly', 'Dolphin', 'Kangaroo', 'Flamingo', 'Hedgehog', 'Chameleon', 'Jellyfish', 'Panda', 'Owl', 'Crocodile', 'Squirrel', 'Peacock', 'Turtle', 'Seahorse', 'Camel', 'Bee', 'Fox', 'Rabbit', 'Snail', 'Bat', 'Lion', 'Tiger', 'Wolf', 'Bear', 'Polar bear', 'Gorilla', 'Monkey', 'Sloth', 'Koala', 'Zebra', 'Hippo', 'Rhino', 'Cheetah', 'Leopard', 'Deer', 'Moose', 'Horse', 'Donkey', 'Cow', 'Pig', 'Sheep', 'Goat', 'Chicken', 'Duck', 'Swan', 'Parrot', 'Eagle', 'Hawk', 'Pigeon', 'Crow', 'Hummingbird', 'Frog', 'Toad', 'Lizard', 'Snake', 'Iguana', 'Shark', 'Whale', 'Seal', 'Otter', 'Lobster', 'Crab', 'Starfish', 'Clownfish', 'Eel', 'Ant', 'Spider', 'Ladybird', 'Mosquito', 'Moth', 'Dragonfly', 'Worm', 'Hamster', 'Guinea pig', 'Mouse', 'Rat'],
  everyday: ['Alarm clock', 'Coffee break', 'Traffic jam', 'Rush hour', 'Umbrella weather', 'Sunday roast', 'Grocery list', 'Self-checkout', 'Loyalty card', 'Receipt', 'Queue', 'Lift', 'Escalator', 'Revolving door', 'Doorbell', 'Neighbour', 'Landlord', 'Rent day', 'Recycling bin', 'Bin day', 'Lost keys', 'Spare key', 'Dead battery', 'Wi-Fi password', 'Group chat', 'Voice note', 'Missed call', 'Selfie', 'Screenshot', 'Autocorrect', 'Spam email', 'Password reset', 'Zoom call', 'Meeting', 'Deadline', 'Lunch break', 'Payday', 'Overtime', 'Sick day', 'Homework', 'Exam', 'School run', 'Packed lunch', 'Detention', 'Library card', 'Dentist appointment', 'Haircut', 'Laundry day', 'Odd sock', 'Ironing', 'Dishwasher', 'Leftovers', 'Takeaway', 'Delivery driver', 'Doorstep parcel', 'Wrong address', 'Junk drawer', 'Spring cleaning', 'Houseplant', 'Pet hair', 'Dog walk', 'Litter tray', 'Morning run', 'Gym membership', 'Step count', 'Snooze button', 'Late night snack', 'Netflix binge', 'Spoiler', 'Playlist', 'Earphones', 'Charger cable', 'Bus pass', 'Parking ticket', 'Speed bump', 'Roundabout', 'Road trip', 'Boarding pass', 'Airport security', 'Jet lag', 'Suitcase wheel', 'Hotel breakfast', 'Souvenir', 'Postcard', 'Sunburn', 'Mosquito bite', 'Rainy day', 'Heatwave', 'Snow day', 'Power cut', 'Birthday reminder', 'Secret Santa', 'Housewarming gift', 'Thank-you note', 'Small talk', 'Awkward silence', 'Inside joke', 'Nickname', 'Handshake', 'High five', 'Yawn', 'Hiccups', 'Sneeze', 'Bad hair day'],
  places: ['Library', 'Airport', 'Beach', 'Museum', 'Cinema', 'Supermarket', 'Lighthouse', 'Castle', 'Aquarium', 'Bakery', 'Playground', 'Train station', 'Desert', 'Waterfall', 'Campsite', 'Stadium', 'Treehouse', 'Restaurant', 'Mountain', 'Zoo', 'Garden', 'Swimming pool', 'Farm', 'Island', 'Hospital', 'School', 'Office', 'Gym', 'Theatre', 'Concert hall', 'Nightclub', 'Casino', 'Hotel', 'Hostel', 'Cafe', 'Pub', 'Food truck', 'Market', 'Shopping mall', 'Petrol station', 'Car wash', 'Garage', 'Bus stop', 'Harbour', 'Ferry', 'Subway', 'Bridge', 'Tunnel', 'Skyscraper', 'Cathedral', 'Temple', 'Cemetery', 'Prison', 'Courtroom', 'Police station', 'Fire station', 'Post office', 'Bank', 'Pharmacy', 'Dentist', 'Hair salon', 'Laundromat', 'Bookshop', 'Toy shop', 'Ice rink', 'Bowling alley', 'Arcade', 'Theme park', 'Water park', 'Circus', 'Ski resort', 'Volcano', 'Cave', 'Jungle', 'Canyon', 'Glacier', 'Lake', 'River', 'Vineyard', 'Orchard'],
  objects: ['Umbrella', 'Telescope', 'Toothbrush', 'Backpack', 'Candle', 'Scissors', 'Guitar', 'Mirror', 'Headphones', 'Compass', 'Camera', 'Ladder', 'Bicycle', 'Pillow', 'Kite', 'Suitcase', 'Key', 'Clock', 'Sunglasses', 'Balloon', 'Book', 'Magnet', 'Paintbrush', 'Teapot', 'Laptop', 'Phone charger', 'Remote control', 'Batteries', 'Lightbulb', 'Extension cord', 'Hairdryer', 'Toaster', 'Kettle', 'Fridge', 'Microwave', 'Blender', 'Frying pan', 'Chopsticks', 'Corkscrew', 'Thermos', 'Lunchbox', 'Wallet', 'Passport', 'Ticket', 'Stamp', 'Envelope', 'Notebook', 'Pencil', 'Stapler', 'Calculator', 'Ruler', 'Glue stick', 'Tape', 'Whiteboard', 'Trophy', 'Medal', 'Piggy bank', 'Dice', 'Playing cards', 'Puzzle', 'Teddy bear', 'Skateboard', 'Helmet', 'Tent', 'Sleeping bag', 'Torch', 'Binoculars', 'Fishing rod', 'Hammer', 'Screwdriver', 'Drill', 'Wheelbarrow', 'Hose', 'Broom', 'Vacuum cleaner', 'Bucket', 'Doormat', 'Curtains', 'Alarm clock', 'Hammock'],
  activities: ['Camping', 'Dancing', 'Swimming', 'Gardening', 'Baking', 'Fishing', 'Skiing', 'Painting', 'Bowling', 'Surfing', 'Hiking', 'Singing', 'Knitting', 'Skateboarding', 'Reading', 'Yoga', 'Juggling', 'Sailing', 'Chess', 'Karaoke', 'Picnic', 'Running', 'Photography', 'Football', 'Cycling', 'Jogging', 'Rock climbing', 'Bungee jumping', 'Skydiving', 'Scuba diving', 'Snorkelling', 'Kayaking', 'Ice skating', 'Snowboarding', 'Sledging', 'Horse riding', 'Archery', 'Fencing', 'Boxing', 'Wrestling', 'Golf', 'Tennis', 'Basketball', 'Volleyball', 'Badminton', 'Table tennis', 'Darts', 'Pool', 'Poker', 'Bingo', 'Sudoku', 'Crossword', 'Video games', 'Board games', 'Drawing', 'Sculpting', 'Pottery', 'Origami', 'Sewing', 'Woodwork', 'Cooking', 'Grilling', 'Wine tasting', 'Bird watching', 'Stargazing', 'Meditation', 'Sunbathing', 'Window shopping', 'Thrifting', 'Busking', 'Beatboxing', 'DJing', 'Ballet', 'Breakdancing', 'Cheerleading', 'Magic tricks', 'Stand-up comedy', 'Acting', 'Podcasting', 'Vlogging'],
  'date-night': ['Candlelight', 'Bouquet', 'Serenade', 'Sunset walk', 'Slow dance', 'Love letter', 'First kiss', 'Rooftop dinner', 'Wine tasting', 'Stargazing', 'Proposal', 'Anniversary', 'Chocolate fondue', 'Rose', 'Piano bar', 'Movie night', 'Hand-holding', 'Fireplace', 'Karaoke duet', 'Picnic blanket', 'Photo booth', 'Long-distance call', 'Blind date', 'Honeymoon', 'Sunrise hike', 'Cooking together', 'Dessert for two', 'Long drive', 'Ferris wheel', 'Rooftop bar', 'Jazz club', 'Ice cream date', 'Hot tub', 'Bubble bath', 'Breakfast in bed', 'Couples massage', 'Ballroom dancing', 'Salsa class', 'Pottery date', 'Paint and sip', 'Escape room date', 'Mini golf', 'Bowling date', 'Board game night', 'Fancy dress', 'Flower crown', 'Love song', 'Mixtape', 'Matching pyjamas', 'Weekend away', 'Beach picnic', 'Ferry ride', 'Lantern release', 'Fortune cookie', 'Cheese board', 'Champagne toast', 'Balcony breakfast'],
  halloween: ['Pumpkin', 'Jack-o’-lantern', 'Witch', 'Broomstick', 'Cauldron', 'Black cat', 'Vampire', 'Werewolf', 'Zombie', 'Mummy', 'Ghost', 'Skeleton', 'Haunted house', 'Graveyard', 'Tombstone', 'Coffin', 'Spider web', 'Bat', 'Full moon', 'Scarecrow', 'Trick-or-treat', 'Candy corn', 'Costume', 'Mask', 'Fake blood', 'Fog machine', 'Ouija board', 'Crystal ball', 'Fortune teller', 'Frankenstein', 'Grim reaper', 'Scythe', 'Potion', 'Spell book', 'Cobweb', 'Haunted maze', 'Horror movie', 'Jump scare', 'Creepy clown', 'Chainsaw', 'Trapdoor', 'Creaky door', 'Raven', 'Wolf howl', 'Candy bucket', 'Doorbell', 'Ghost story', 'Hearse'],
  football: ['Penalty', 'Free kick', 'Corner kick', 'Offside', 'Red card', 'Yellow card', 'Own goal', 'Hat-trick', 'Golden Boot', 'Clean sheet', 'Goalkeeper', 'Striker', 'Winger', 'Captain’s armband', 'Referee', 'VAR', 'Extra time', 'Penalty shootout', 'Stoppage time', 'Derby', 'Champions League', 'World Cup', 'Premier League', 'Transfer window', 'Mascot', 'Stadium', 'Dugout', 'Half-time', 'Nutmeg', 'Bicycle kick', 'Header', 'Volley', 'Sliding tackle', 'Dive', 'Throw-in', 'Defensive wall', 'Crossbar', 'Top corner', 'Season ticket', 'Away end', 'Chant', 'Scarf', 'Home kit', 'Shin pads', 'Manager', 'Substitute', 'Relegation', 'Ballon d’Or', 'Goal-line technology', 'Penalty box', 'Six-yard box', 'Kick-off', 'Coin toss', 'Handshake', 'Anthem', 'Line-up', 'Formation', 'Set piece', 'Counter-attack', 'Long ball', 'Through ball', 'Back pass', 'Rabona', 'Panenka', 'Clean strike', 'Rebound', 'Deflection', 'Goal kick', 'Injury time', 'Man of the match', 'Golden goal', 'Aggregate', 'Play-offs', 'Promotion', 'Treble', 'Invincibles', 'Underdogs', 'Tifo', 'Pitch invasion', 'Half-time pie'],
  'k-pop': ['Bias', 'Bias wrecker', 'Comeback', 'Lightstick', 'Fan chant', 'Photocard', 'Maknae', 'Leader', 'Visual', 'Main vocal', 'Rap line', 'Choreography', 'Point dance', 'Title track', 'B-side', 'Music show', 'Encore', 'Fan sign', 'Trainee', 'Debut', 'Aegyo', 'Sub-unit', 'Concept photo', 'Teaser', 'Album unboxing', 'Fandom name', 'Lightstick ocean', 'Kill part', 'Line distribution', 'Idol', 'Survival show', 'Center', 'Ending fairy', 'Selca', 'BTS', 'Blackpink', 'Stray Kids', 'NewJeans', 'Twice', 'Seventeen', 'aespa', 'EXO', 'Red Velvet', 'Le Sserafim', 'ITZY', 'NCT', 'Enhypen', 'IVE', 'Photobook', 'Pre-order', 'Fan cafe', 'Fan meeting', 'Fansite', 'Lightstick battery', 'Comeback stage', 'Dance practice video', 'Relay dance', 'Random play dance', 'Cover dance', 'High note', 'Ad-lib', 'Killing part', 'Concept trailer', 'Highlight medley', 'Tracklist', 'Repackage', 'Special stage', 'Award show', 'Daesang', 'Rookie of the year', 'Hiatus', 'Solo debut', 'Variety show', 'Idol reality show', 'Weverse', 'Dance challenge', 'Hashtag trend', 'Stan', 'Sasaeng', 'Bias list'],
  'pop-superstars': ['Anti-Hero', 'Cruel Summer', 'Folklore', 'Eras Tour', 'Love Story', 'Shake It Off', 'Espresso', 'Flowers', 'Bad Guy', 'Drivers License', 'Renaissance', 'Single Ladies', 'Umbrella', 'Diamonds', 'Blinding Lights', 'Uptown Funk', 'Rolling in the Deep', 'Toxic', 'Poker Face', 'Bad Romance', 'Thriller', 'Billie Jean', 'Like a Prayer', 'Dancing Queen', 'Bohemian Rhapsody', 'Firework', 'Chandelier', 'Levitating', 'Good 4 U', 'Watermelon Sugar', 'As It Was', 'Shape of You', 'Havana', 'Kill Bill', 'Padam Padam', 'Taylor Swift', 'Beyoncé', 'Rihanna', 'Lady Gaga', 'Dua Lipa', 'Harry Styles', 'Billie Eilish', 'Olivia Rodrigo', 'Sabrina Carpenter', 'Chappell Roan', 'Ariana Grande', 'The Weeknd', 'Adele', 'Vampire', 'Greedy', 'Houdini', 'Paint the Town Red', 'About Damn Time', 'Truth Hurts', 'Señorita', 'Perfect', 'Don’t Start Now', 'Happier Than Ever', 'Hello', 'Halo', 'Purple Rain', 'Vogue', 'Roar', 'Sorry', 'Believe', 'Wannabe', 'Baby One More Time', 'Crazy in Love', 'Hips Don’t Lie', 'Since U Been Gone', 'Call Me Maybe', 'Royals', 'Shallow', 'Bad Habits', 'Stay', 'Flowers in your hair', 'Miley Cyrus', 'Katy Perry', 'Justin Bieber', 'Shakira'],
  christmas: ['Christmas tree', 'Mistletoe', 'Stocking', 'Chimney', 'Sleigh', 'Reindeer', 'Rudolph', 'Elf', 'North Pole', 'Snowman', 'Gingerbread house', 'Candy cane', 'Eggnog', 'Mulled wine', 'Turkey dinner', 'Cranberry sauce', 'Brussels sprouts', 'Christmas pudding', 'Mince pie', 'Advent calendar', 'Wreath', 'Tinsel', 'Bauble', 'Fairy lights', 'Star on top', 'Nativity scene', 'Carol singers', 'Secret Santa', 'Wrapping paper', 'Ugly sweater', 'Christmas market', 'Ice skating', 'Snowball fight', 'Hot chocolate', 'Nutcracker', 'The Grinch', 'Home Alone', 'Santa’s workshop', 'Naughty list', 'Letter to Santa', 'Christmas Eve', 'Boxing Day', 'Christmas cracker', 'Paper crown', 'Yule log', 'Snow globe', 'Sledging', 'Roast chestnuts'],
  holidays: ['Fireworks', 'Christmas tree', 'Menorah', 'Pumpkin', 'Firecracker', 'New Year', 'Easter egg', 'Parade', 'Costume', 'Mistletoe', 'Carnival', 'Lantern festival', 'Turkey dinner', 'Snowman', 'Gift wrap', 'Countdown', 'Candy cane', 'Trick-or-treat', 'Fourth of July', 'Wreath', 'Valentine’s Day', 'Diwali', 'Piñata', 'Harvest festival', 'Birthday cake', 'Surprise party', 'Confetti', 'Balloon arch', 'Party hat', 'Karaoke night', 'Bonfire night', 'Sparkler', 'Easter bunny', 'Chocolate egg', 'Pumpkin pie', 'Gingerbread man', 'Advent wreath', 'Dreidel', 'Diwali lamp', 'Lunar New Year', 'Red envelope', 'Dragon dance', 'Mardi Gras beads', 'St Patrick’s Day', 'Shamrock', 'Mother’s Day', 'Father’s Day', 'Graduation cap', 'Wedding cake', 'First dance', 'Baby shower', 'Housewarming', 'Retirement party', 'Anniversary dinner', 'Toast', 'Champagne', 'Midnight kiss'],
};
export const words: Word[] = Object.entries(packs).flatMap(([category, entries]) => entries.map((text, index) => ({ id: `${category}-${index}`, text, category: category as Word['category'] })));
const mixedCategoryIds = new Set<Word['category']>(categories.filter(category => !category.premium && category.group === 'core' && category.id !== 'mixed').map(category => category.id) as Word['category'][]);
// The free "mixed" pool blends only free core packs: never a premium word for a non-premium
// player, and never a Halloween word in June.
export function getWords(category: Category) {
  if (category === 'mixed') return words.filter(word => mixedCategoryIds.has(word.category));
  return words.filter(word => word.category === category);
}
